name: gcr.io_mirror

on: 
  issues:
    types: [opened, edited]
  label:
    types: [created]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'porter')
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 golang 环境
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          check-latest: true
          cache: true

      - name: 运行 go 代码
        run: go run main.go --github.token=${{ secrets.GITHUB_TOKEN }} --github.user=${{ github.repository_owner }} --github.repo=${{ github.event.repository.name }} --docker.registry=${{ secrets.DOCKER_REGISTRY }} --docker.namespace=${{ secrets.DOCKER_NAMESPACE }} --docker.user=${{ secrets.DOCKER_USER }} --docker.secret=${{ secrets.DOCKER_PASSWORD }} --github.run_id=${{ github.run_id }}

  auto_close_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Automatically close issues that don't follow the issue template
        uses: lucasbento/auto-close-issues@28e2d2bff4035cd60111c3e1fa4d0145875fabd9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-close-message: "@${issue.user.login}: hello! :wave:\n\nThis issue is being automatically closed because it does not follow the issue template." # optional property